spring:
  application:
    name: backend
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/asskicker?authSource=admin
app:
  security:
    jwt:
      secret: change-this-secret-to-32-chars-minimum
      access-token-ttl: PT24H
      refresh-token-ttl: PT720H
logging:
  async:
    queue-size: 1024
    discarding-threshold: 0
server:
  port: 8080
